version: "3.6"

# this creates a mail relay server on the host IP on default port 25. Just use it.

services:
  pmail:
    build:
      context: .
      dockerfile: ./pfix.Dockerfile
    restart: always
    ports:
       - "25:25"
    environment:
      # MAIL_RELAY_HOST: smtp.gmail.com 
      # MAIL_RELAY_HOST: mail.wightman.ca 
      MAIL_RELAY_HOST: smtp-mail.outlook.com 
      MAIL_RELAY_PORT: 587 
      # ROUTE_CUSTOM: "192.168.0.0/16 172.0.0.0/8 10.0.0.0/8"       
      ROUTE_CUSTOM: "192.168.88.0/24"       
      # see .env for user/pass
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "9"      


# from readme...      
# docker container run \
#     -e MAIL_RELAY_HOST='smtp.gmail.com' \
#     -e MAIL_RELAY_PORT='587' \
#     -e MAIL_RELAY_USER='your_gmail_addr@gmail.com' \
#     -e MAIL_RELAY_PASS='your_gmail_pass' \
#     tecnativa/postfix-relay

