version: "3"

services:
  appsmith:
  # http://10.5.1.131:8031
    image: index.docker.io/appsmith/appsmith-ce:v1.9.22
    # container_name: appsmith
    ports:
      - "8031:80"
      - "4431:443"
      - "9031:9001"
    volumes:
      - ../sysdata/stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped  

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --interval 300 --label-enable --cleanup
    restart: unless-stopped