# Generated by Django 4.1.7 on 2023-03-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapplication', models.CharField(max_length=330)),
                ('mstatus', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mdescription', models.CharField(max_length=330)),
                ('mcomment', models.CharField(max_length=330)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msort', models.IntegerField(default=50)),
                ('mlink', models.CharField(max_length=930)),
            ],
        ),
    ]
