# Generated by Django 4.1.7 on 2023-03-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu0',
            name='mgroup',
            field=models.CharField(blank=True, max_length=330, null=True),
        ),
        migrations.AlterField(
            model_name='menu0',
            name='mcomment',
            field=models.CharField(blank=True, max_length=330, null=True),
        ),
    ]
