version: "3.7"

networks:
  net574:
    name: net574
   
volumes:
  postgresdata:

services:

  mb:
    # http://10.4.71.231:6536/
    # image: metabase/metabase:v0.40.5
    image: metabase/metabase:v0.45.3
    restart: always
    ports:
      - "6536:3000"
    volumes:
      - ../data/mbdata:/mbdata
    env_file:
      - .env
    # depends_on:
    #   - dbm
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    networks:
      - net574
  

  dbp:
    image: "postgres:15-alpine"
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "16432:5432"
    volumes:
      - ../sysdata/postgres/data:/var/lib/postgresql/data
      networks:
        - net574

  # dbm:
    # image: mysql:5.7
    # ports: 
      # - 6534:3306
    # restart: unless-stopped  
    # env_file:
      # - .env
    # volumes:
      # # folder for mysql's internal data files.
      # # - mysqldata:/var/lib/mysql
      # # - ../datasys/mysql${PWD}:/var/lib/mysql/  
      # - ../sysdata/mysql_data:/var/lib/mysql/ 
      # # init data scripts..
      # - ./mysql-init/:/docker-entrypoint-initdb.d/
      # # folder for scripts, etc.
      # - ./script:/script
      # # folder for exported/imported data, etc.
      # - ../data/mydat/:/mydat
    # command: --default-authentication-plugin=mysql_native_password
    # logging:
      # driver: "json-file"
      # options:
        # max-size: "100k"
        # max-file: "3"
    # healthcheck:
      # test: ["CMD", ping", "-c 2", "localhost"]
      # interval: 1m30s
      # timeout: 20s
      # retries: 3
      # start_period: 60s
    # networks:
      # - net574 


  adminer:
    # 10.4.1.231:6117/
    image: adminer:4.7
    restart: unless-stopped
    ports:
      - 6535:8080
    environment:
      - ADMINER_DEFAULT_SERVER=dbp
      # - ADMINER_PLUGINS='tables-filter tinymce'
    networks:
      - net574
