# This is the recommended way of running Baserow using docker-compose for most users.
# See https://baserow.io/docs/installation%2Finstall-with-docker for more details.

# from all-in-one


version: "3.4"
services:
  baserow:
    #  http://http://10.5.1.131:7001
    container_name: baserow705b
    image: baserow/baserow:1.21.2
    environment:
      BASEROW_PUBLIC_URL: 'http://10.5.1.131'
      WEB_FRONTEND_SSL_PORT: '444'
      WEB_FRONTEND_PORT: '7001'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:


