# =================================================
# docker-compose.yaml
version: "3"
networks:
    default:
        name: ${STACK_PRFX}
services:
  # Cache
  cache:
    container_name: ${STACK_PRFX}-cache
    image: redis:7.0-alpine
  # Directus
  directus:
    # http://192.168.88.55:8055/  
    container_name: ${STACK_PRFX}-directus
    image: directus/directus:9.22.1
    restart: unless-stopped
    ports:
        - 8055:8055
    volumes:
        - ./uploads:/directus/uploads
    depends_on:
        - cache
        # - database
    env_file:
        - .env

  database:
    image: yobasystems/alpine-mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      # - ../sysdata/mysql705/appdata:/app
      # - /etc/localtime:/etc/localtime:ro
      # folder for mysql's internal data files. permanent store on local folder.. 
      - ../sysdata/${STACK_PRFX}/mariadbalpine:/var/lib/mysql/ 
    ports:
      - "8308:3306"
    command:
        [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-authentication-plugin=mysql_native_password",
        ]
    env_file:
        - .env

  adminer:
    # http://192.168.88.55:8309/  
    # use dbm or ip:port for server while logging in.
    image: adminer:4.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_PLUGINS=tables-filter
    ports:
      - 8309:8080
    # networks:
    #   - sister2
    
# =================================================

#   example sqlite3

# version: '3'
# services:
  # directus:
    # image: directus/directus:latest
    # ports:
      # - 8055:8055
    # volumes:
      # - ../sysdata/${STACK_PRFX}/uploads:/directus/uploads
      # - ../sysdata/${STACK_PRFX}/database:/directus/database
    # environment:
      # KEY: '255d861b-599-9aa3-922530ec40b1'
      # SECRET: '6116487b-52c-b5b5-c8022c45e263'

      # DB_CLIENT: 'sqlite3'
      # DB_FILENAME: './database/data.db'

      # ADMIN_EMAIL: 'admin@example.com'
      # ADMIN_PASSWORD: 'd1r3ctu5'

# =================================================
