version: '3.6'

# networks:
  # sister627:
    # name: sister627

services:

  nocodb:
    # http://10.5.1.129:9082
    # depends_on:
    #   - root_db
      # condition: service_healthy 
    image: nocodb/nocodb:0.106.1
    ports:
      - "9082:8080"
    restart: always
    env_file: [ .env ]
    environment:
      # see .env
      example_works_NC_DB: "mysql2://root_db:3306?u=noco&p=dbpass&d=root_db"
    volumes:
      - ../sysdata/noco_data:/usr/app/data/


  # dbp:
    # image: "postgres:15-alpine"
    # restart: unless-stopped
    # env_file:
      # - ./.env
    # ports:
      # - "25432:5432"
    # volumes:
      # - ../sysdata/postgres/data:/var/lib/postgresql/data



  adminer:
    # http://10.5.1.129:9182/
    image: adminer:4.7
    restart: unless-stopped
    ports:
      - 9182:8080
    environment:
      - ADMINER_DEFAULT_SERVER=dbp
      # - ADMINER_PLUGINS='tables-filter tinymce'
    # networks:
      # - net574


# use 618mysql not this....

  # root_db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   env_file: [ .env ]
  #   environment:
  #     MYSQL_DATABASE: root_db
  #     MYSQL_USER: noco
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #     timeout: 20s
  #     retries: 10
  #   ports:
  #     - "9306:3306"


# volumes:
#   db_data: {}
