
# docker container run -dit -p 14101:5000 --ulimit nofile=1024 -v/omd/sites  -v/etc/localtime:/etc/localtime:ro --restart always 
# https://hub.docker.com/r/checkmk/check-mk-raw/

version: "3.6"

# mail setup
# https://docs.checkmk.com/latest/en/managing_docker.html
#   2.4. Sending notifications

# no need for this. Just run postfix relay docker - postfix-relay-472 . use the host ip and the default port 25
#networks:
#  checkmk_net:
#    name: checkmk_net
    
    #networks:
    #  - checkmk_net
    
 
services:
  checkmk:
    image: checkmk/check-mk-raw:2.2.0-latest
    #image: checkmk/check-mk-raw:2.1.0-latest
    restart: always
    hostname: checkmk.local
    # user: cmk
    ulimits:
      nofile: 1024
    ports:
      - "14101:5000"
    env_file:
      - .env
    volumes:
      - ../datasys/check_mk${PWD}:/omd/sites 
      # no - ./backups:/omd/sites/${CMK_SITE_ID}/backups
      - ./backups:/backups
      - /etc/localtime:/etc/localtime:ro
      #- ../data/mysqlhome${PWD}/:/home # folder for exported data, etc.
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "3"
    # No need for this. Just run the postfix-relay-472 docker project.    
    # depends_on:
    #  - pmail

    
