version: '3'
services:

  dbm:
    build:
      dockerfile: Dockerfile
      context: .
    image: ${IMAGE_NAME}:${ALPINE_VERSION}
    #container_name: ${CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      # - ../sysdata/mysql705/appdata:/app
      - /etc/localtime:/etc/localtime:ro
      # folder for mysql's internal data files. permanent store on local folder.. 
      - ../sysdata/mysqldata:/var/lib/mysql/ 
    ports:
      - "${HOST_ADDRESS}:3306"

  adminer:
    # http://192.168.88.55:8307/  
    # use dbm or ip:port for server while logging in.
    image: adminer:4.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=dbm
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_PLUGINS=tables-filter
    ports:
      - 8307:8080
    # networks:
    #   - sister2
