# Generated by Django 4.1.7 on 2023-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menumodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapplication', models.CharField(max_length=350)),
                ('mcomment', models.CharField(max_length=230)),
                ('mlink', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mdescription', models.CharField(max_length=1930)),
                ('msort', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mstatus', models.IntegerField()),
                ('mgroup', models.CharField(max_length=430)),
            ],
        ),
    ]
