# Generated by Django 4.1.7 on 2023-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='mcomment',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='mdescription',
            field=models.CharField(blank=True, max_length=1930, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='mgroup',
            field=models.CharField(blank=True, max_length=430, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='mlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='msort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='mstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
